BrainBuilder/BrainBuilder/Models/Profiles.cs
using System;
using System.Collections.Generic;

namespace BrainBuilder.Models
{
    public partial class Profiles
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Bio { get; set; }
        public string Motto { get; set; }
        public string ProvinceCode { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public DateTime? BirthDate { get; set; }
        public bool? PromotionalEmails { get; set; }
        public bool? IsSubscribed { get; set; }

        public virtual Accounts IdNavigation { get; set; }
        public virtual Provinces ProvinceCodeNavigation { get; set; }
    }
}

BrainBuilder/BrainBuilder/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BrainBuilder.Models;

/*
 ********
 * Profiles Controller
 * Controller used for profiles
 * Date Created: 03/03/2021
 * Desert Sands 
 *********
*/

namespace BrainBuilder.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        private readonly BrainBuilderDBContext _context;
        private readonly UserManager<IdentityUser> _userManager;


        public ProfilesController(BrainBuilderDBContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        /// <summary>
        /// Shows account
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(string name)
        {
            string defaultAvatar = "NAN";

            //Gets id of current user
            Accounts account = _context.Accounts.Where(p => p.Username == User.Identity.Name).FirstOrDefault();

            //Gets username from person class for profile page
            ViewData["Name"] = account.Username;

            //Gets information of the correct person
            var profile = await _context.Profiles
                .Include(p => p.ProvinceCodeNavigation)
                .FirstOrDefaultAsync(p => p.Id == account.AccountId);

            //If person is null
            if (profile == null)
            {
                return NotFound();
            }

            //Gets correct avatar
            var avatar = await _context.Avatars
                .FirstOrDefaultAsync(p => p.Id == account.AccountId);

            //Puts avatar code into a ViewData - if null, provide a default avatar
            if (avatar != null)
            {
                ViewData["Avatar"] = avatar.AvatarCode;
            }
            else
            {
                ViewData["Avatar"] = defaultAvatar;
            }

            //Determines if the user has a subscription
            if (profile.IsSubscribed == true)
            {
                ViewData["subscription"] = "MembershipPlus";

                //Checks if the subscription is active
                UserSubscriptions userSubscriptions = _context.UserSubscriptions.Where(u => u.AccountId == account.AccountId).FirstOrDefault();

                if (userSubscriptions.IsActive)
                {
                    ViewData["isActive"] = "T";
                }
                else
                {
                    ViewData["isActive"] = "F";
                }

            }
            else
            {
                ViewData["subscription"] = "Membership";
                ViewData["isActive"] = "F";
            }

            //Determines age for birthdate - if provided
            if (profile.BirthDate != null)
            {
                // Gets date for the age and today's date
                var today = DateTime.Today;
                var birthDate = (DateTime)profile.BirthDate;

                // Calculate the age.
                var age = today.Year - birthDate.Year;

                // Go back to the year in which the person was born in case of a leap year
                if (birthDate.Date > today.AddYears(-age))
                    age--;

                ViewData["age"] = age;
            }
            else
            {
                ViewData["age"] = String.Empty;
            }

            //Checks if the user has any stats
            var stats = await _context.GameStats
                .FirstOrDefaultAsync(p => p.AccountId == account.AccountId);

            //Determines if there are any stats from the user
            if (stats != null)
            {
                ViewData["achievements"] = true;
            }
            else
            {
                ViewData["achievements"] = false;
            }

            return View(profile);
        }

        // GET: Profile/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            string defaultAvatar = "NAN";

            //Gets correct avatar
            var avatar = await _context.Avatars
                .FirstOrDefaultAsync(p => p.Id == id);

            //Puts avatar code into a ViewData - if null, provide a default avatar
            if (avatar != null)
            {
                ViewData["Avatar"] = avatar.AvatarCode;
            }
            else
            {
                ViewData["Avatar"] = defaultAvatar;
            }

            if (id == null)
            {
                TempData["message"] = "Profile not found";
                return RedirectToAction("Index");
            }

            var profile = await _context.Profiles.FindAsync(id);
            if (profile == null)
            {
                TempData["message"] = "Profile not found";
                return RedirectToAction("Index");
            }
            ViewData["Provinces"] = new SelectList(_context.Provinces, "Code", "ProvinceName", profile.ProvinceCode);
            ViewData["Genders"] = DSFillGenderList();
            return View(profile);
        }

        // POST: Profile/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DisplayName,Bio,Motto,ProvinceCode,Gender,BirthDate")] Profiles profile)
        {
            if (id != profile.Id)
            {
                TempData["message"] = "Profile Edit Failed";
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfileExists(profile.Id))
                    {
                        TempData["message"] = "Profile Edit Failed";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { User.Identity.Name });
            }
            ViewData["Provinces"] = new SelectList(_context.Provinces, "Code", "ProvinceName", profile.ProvinceCode);
            ViewData["Genders"] = DSFillGenderList();
            ViewData["Genders"] = DSFillGenderList(profile.Gender);
            return View(profile);
        }

        /// <summary>
        /// Determines if a certain profile exists
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool ProfileExists(int id)
        {
            return _context.Profiles.Any(e => e.Id == id);
        }

        /// <summary>
        /// Fills a selectlist with possible gender selections
        /// </summary>
        /// <returns></returns>
        public SelectList DSFillGenderList(string input = "")
        {
            List<string> genders = new List<string>();

            genders.Add("");
            genders.Add("Male");
            genders.Add("Female");
            genders.Add("Other");

            return new SelectList(genders, input);
        }

    }
}

BrainBuilder/BrainBuilder/Views/Profiles/Details.cshtml
@model BrainBuilder.Models.Profiles
@using Microsoft.AspNetCore.Identity
@{
    string avatarLink = "https://avatars.dicebear.com/api/identicon/" + ViewData["Avatar"] + ".svg";
    ViewData["Title"] = ViewData["Name"] + "'s Profile";
    string membership = ViewData["subscription"].ToString();
    string isActive = ViewData["isActive"].ToString();
    bool hasAchievements = (bool) ViewData["achievements"];
}

<header class="py-5"></header>
<section>
    <div class="container">
        <h1>@ViewData["Title"]</h1>
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div id="cardProfileHeader" class="profileCard">
                    <div class="profileCard-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="@avatarLink" alt="@Html.DisplayFor(model => model.DisplayName)" class="rounded profilePicture" width="150">
                            <div class="mt-3">
                                @if (membership == "MembershipPlus")
                                {
                                    if (isActive == "T")
                                    {
                                        <img id="imgMembershipPlusBadge" src="~/img/vip.png" alt="Membership+ Activated" width="25">
                                    }
                                    else
                                    {
                                        <img id="imgMembershipPlusBadgeInactive" class="subscriptionInactive" src="~/img/vip.png" alt="Membership+ Activated" width="25">
                                    }

                                }
                                <h4 id="lblName">@Html.DisplayFor(model => model.DisplayName)</h4>
                                <p id="lblMotto" class="text-muted font-size-sm">@Html.DisplayFor(model => model.Motto)</p>
                                @if (User.Identity.Name == ViewData["Name"].ToString())
                                {
                                    <a asp-action="Edit" id="btnEditProfile" asp-controller="Profiles" asp-route-id="@Model.Id" class="btn btn-secondary">Edit Profile</a>
                                    <a class="btn btn-primary" id="btnManageUser" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Profile Settings</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div id="cardAchievements "class="profileCard mt-3">
                    <div class="d-flex flex-column align-items-center text-center">
                        <div class="mt-3">
                            <h2>Achievements</h2>
                        </div>
                        <hr />
                        @if (hasAchievements == true)
                        {
                            <ul class="list-group list-group-flush">
                                You have completed a game.
                            </ul>
                        }
                        else
                        {
                            <ul class="list-group list-group-flush">
                                You have not completed a game.
                            </ul>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div id="cardProfileInformation" class="profileCard mb-3">
                    <div class="profileCard-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Nickname</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @Html.DisplayFor(model => model.DisplayName)
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Bio</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @Html.DisplayFor(model => model.Bio)
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @Html.DisplayFor(model => model.IdNavigation.Email)
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Province</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @Html.DisplayFor(model => model.ProvinceCodeNavigation.ProvinceName)
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Age</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @ViewData["age"]
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

BrainBuilder/BrainBuilder/Views/Profiles/Edit.cshtml
@model BrainBuilder.Models.Profiles
@using Microsoft.AspNetCore.Identity

@{
    string avatarLink = "https://avatars.dicebear.com/api/identicon/" + ViewData["Avatar"] + ".svg";
    ViewData["Title"] = "Edit";
}

<header class="py-5"></header>
<section>
    <div class="container">
        <h4>Edit your Profile</h4>

        <form asp-action="Edit" id="frmEditProfile" onsubmit="return DSValidation();">
            <input type="hidden" asp-for="Id" />
            <div class="row gutters-sm">

                <div class="col-md-4 mb-3">
                    <div id="cardProfileHeader" class="profileCard">
                        <div class="profileCard-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="@avatarLink" alt="@Html.DisplayFor(model => model.DisplayName)" class="rounded profilePicture" width="150">
                                <div class="mt-3">
                                    <label asp-for="DisplayName" class="control-label"></label>
                                    <input asp-for="DisplayName" id="txtDisplayName" class="form-control" />
                                    <span id="txtDisplayName-error" asp-validation-for="DisplayName" class="text-danger"></span>
                                    <label asp-for="Motto" class="control-label"></label>
                                    <textarea asp-for="Motto" id="txtMotto" class="form-control"></textarea>
                                    <span id="txtMotto-error" asp-validation-for="Motto" class="text-danger"></span>
                                    <br />
                                    <a asp-action="Details" id="btnCancelEdit" asp-controller="Profiles" class="btn btn-secondary">Cancel</a>
                                    <input type="submit" value="Save" id="btnSave" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div id="cardProfileInformation" class="profileCard mb-3">
                        <div class="profileCard-body">
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Bio</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <textarea asp-for="Bio" id="txtBio" class="form-control"></textarea>
                                    <span asp-validation-for="Bio" id="txtBio-error" class="text-danger"></span>
                                </div>
                            </div>

                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Province</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <select id="ProvinceDropDown" asp-for="ProvinceCode" class="form-control" asp-items="ViewBag.Provinces"></select>
                                    <span id="ProvinceDropDown-error" asp-validation-for="ProvinceCode" class="text-danger"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">I was born on...</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input id="txtBirthDate" asp-for="BirthDate" class="form-control" type="date"/>
                                    <span id="txtBirthDate-error" asp-validation-for="BirthDate" class="text-danger"></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Gender</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <select id="GenderDropDown" asp-for="Gender" class="form-control" asp-items="ViewBag.Genders"></select>
                                    <span id="GenderDropDown-error" asp-validation-for="Gender" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
@section Scripts {

    <script type="text/javascript">
        //Validates few validatable fields
        function DSValidation() {
            var noErrors = true;
            //declare variables for input and error field
            var displayName = document.getElementById('txtDisplayName').value;
            var displayNameError = document.getElementById('txtDisplayName-error');

            if (displayName == null || displayName.trim() == "") {
                displayNameError.innerHTML = "Display Name cannot be empty";
                noErrors = false;
            }
            else {
                displayName.innerHTML = "";
            }

            return noErrors;
        }
    </script>
}